[package]
name = "uds-actor-client"
version = "0.1.0"
edition = "2024"

[dependencies.macros]
path = "../macros"

[dependencies]
fltk = { version = "^1.5", features = ["fltk-bundled"] }
reqwest = { version = "0.12.23", features = ["json"] }
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
anyhow = "1.0.88"

[build-dependencies]
chrono = "0.4.42"
winres = "0.1.12"
