[package]
name = "uds-actor-client"
version = "0.1.0"
edition = "2024"

[dependencies.macros]
path = "../macros"

[dependencies]
shared = { path = "../shared", features = ["tokio"] }

tokio = { version = "1.47.1", features = ["macros", "rt", "time"] }

reqwest = { version = "0.12.23", features = ["json", "rustls-tls"] }
serde = { version = "1.0.227", features = ["derive"] }
serde_json = "1.0.145"
anyhow = "1.0.88"

fltk = { version = "^1.5", features = ["fltk-bundled"] }

[build-dependencies]
chrono = "0.4.42"
winres = "0.1.12"


[dev-dependencies]
mockito = "1.7.0"
