[package]
name = "uds-actor-client"
version = "0.1.0"
edition = "2024"

[dependencies.macros]
path = "../macros"

# Win32::{Foundation::*, System::LibraryLoader::GetModuleHandleW, UI::WindowsAndMessaging::*},
# Windows dependencies
[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.1", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_Graphics_Gdi",
    "Win32_Security",
] }
widestring = "1.2.0"

[dependencies]
shared = { path = "../shared" }

fltk = { version = "^1.5", features = ["fltk-bundled"] }
reqwest = { version = "0.12.23", default-features = false, features = [
    "json",
    "blocking",
    "rustls-tls",
] }
serde = { version = "1.0.227", features = ["derive"] }
serde_json = "1.0.145"
anyhow = "1.0.88"

[build-dependencies]
chrono = "0.4.42"
winres = "0.1.12"

[dev-dependencies]
mockito = "1.7.0"
