[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[features]
# Default features
tokio = ["dep:tokio"]

# Windows dependencies
[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.1", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_Graphics_Gdi",
    "Win32_Security",
] }
widestring = "1.2.0"

[dependencies]
# Logging
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tracing-log = "0.2.0"

tokio = { version = "1.47.1", optional=true, features = ["macros", "rt", "time"] }
